name: AppBlocks.MySqlService

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies - ${{github.workflow}}.sln
      run: dotnet restore src/${{github.workflow}}/${{github.workflow}}.sln
    - name: Build - src/${{github.workflow}}/${{github.workflow}}.sln
      run: dotnet build --no-restore --configuration Release src/${{github.workflow}}/${{github.workflow}}.sln
    - name: Pack - src/${{github.workflow}}/${{github.workflow}}.sln
      run: dotnet pack -v normal -c Release --no-restore --include-symbols --include-source src/${{github.workflow}}/${{github.workflow}}.sln
    - name: Publish - src/${{github.workflow}}/${{github.workflow}}/bin/Release/${{github.workflow}}.*.nupkg
      run: dotnet nuget push src/${{github.workflow}}/${{github.workflow}}/bin/Release/${{github.workflow}}.*.nupkg --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
      
      
      
      








